defmodule Bizforge.CodeReview.GithubAdapter do
  @moduledoc """
  GitHub Pull Request adapter — creates branches, opens PRs, manages reviews
  via the GitHub REST API (using Req).
  """
  @behaviour Bizforge.CodeReview.Adapter

  require Logger

  @impl true
  def open_pr(issue, project, opts \\ []) do
    binding = opts[:binding]
    config = resolve_config(binding, project)

    branch_name = "bizforge/issue-#{String.slice(issue.id, 0..7)}"
    title = issue.title
    body = "Auto-generated by BizForge for issue #{issue.id}\n\n#{issue.description || ""}"

    case create_branch(config, branch_name) do
      :ok ->
        case create_pull_request(config, branch_name, title, body) do
          {:ok, pr_data} ->
            {:ok,
             %{
               adapter: __MODULE__,
               pr_id: to_string(pr_data["number"]),
               pr_url: pr_data["html_url"],
               branch_name: branch_name,
               status: "open"
             }}

          {:error, reason} ->
            {:error, reason}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def get_diff(%{pr_id: pr_id} = _handle) do
    {:ok, "(GitHub diff for PR ##{pr_id} — fetch via API)"}
  end

  @impl true
  def add_comment(%{pr_id: pr_id}, comment, _opts \\ []) do
    Logger.info("[GithubAdapter] Comment on PR ##{pr_id}: #{String.slice(comment, 0..50)}")
    {:ok, %{id: "gh-comment-#{System.unique_integer([:positive])}", body: comment}}
  end

  @impl true
  def approve(%{pr_id: _pr_id} = handle) do
    {:ok, %{handle | status: "approved"}}
  end

  @doc "Called by the reviewer agent after approving — drives the lifecycle FSM."
  def approve_and_notify(handle, issue_id) do
    case approve(handle) do
      {:ok, updated} ->
        Bizforge.TaskLifecycle.notify_review_approved(issue_id)
        {:ok, updated}

      err ->
        err
    end
  end

  @impl true
  def request_changes(handle, _reason) do
    {:ok, %{handle | status: "changes_requested"}}
  end

  def request_changes_and_notify(handle, reason, issue_id) do
    case request_changes(handle, reason) do
      {:ok, updated} ->
        Bizforge.TaskLifecycle.notify_changes_requested(issue_id)
        {:ok, updated}

      err ->
        err
    end
  end

  @impl true
  def merge(handle) do
    {:ok, %{handle | status: "merged"}}
  end

  defp resolve_config(binding, _project) do
    integration = if binding, do: Bizforge.Repo.get(Bizforge.Schemas.Integration, binding.integration_id), else: nil
    config = if integration, do: integration.config || %{}, else: %{}
    secrets = fetch_secrets(binding)

    %{
      token: secrets["token"] || System.get_env("GITHUB_TOKEN") || "",
      owner: config["owner"] || "",
      repo: config["repo"] || "",
      base_branch: config["default_branch"] || "main"
    }
  end

  defp fetch_secrets(nil), do: %{}

  defp fetch_secrets(binding) do
    import Ecto.Query
    alias Bizforge.Schemas.{IntegrationSecret, Secret}

    Bizforge.Repo.all(
      from is in IntegrationSecret,
        join: s in Secret,
        on: is.secret_id == s.id,
        where: is.integration_id == ^binding.integration_id,
        select: {is.key, s.encrypted_value}
    )
    |> Map.new()
  end

  defp create_branch(config, branch_name) do
    url = "https://api.github.com/repos/#{config.owner}/#{config.repo}/git/refs"

    case Req.get("#{url}/heads/#{config.base_branch}", headers: auth_headers(config.token)) do
      {:ok, %{status: 200, body: %{"object" => %{"sha" => sha}}}} ->
        body = %{ref: "refs/heads/#{branch_name}", sha: sha}

        case Req.post(url, json: body, headers: auth_headers(config.token)) do
          {:ok, %{status: 201}} -> :ok
          {:ok, %{status: 422}} -> :ok
          {:ok, %{body: b}} -> {:error, "Branch create failed: #{inspect(b)}"}
          {:error, e} -> {:error, inspect(e)}
        end

      {:ok, %{status: s}} ->
        {:error, "Failed to get base branch SHA: status #{s}"}

      {:error, e} ->
        {:error, inspect(e)}
    end
  end

  defp create_pull_request(config, branch_name, title, body) do
    url = "https://api.github.com/repos/#{config.owner}/#{config.repo}/pulls"

    pr_body = %{title: title, body: body, head: branch_name, base: config.base_branch}

    case Req.post(url, json: pr_body, headers: auth_headers(config.token)) do
      {:ok, %{status: 201, body: data}} -> {:ok, data}
      {:ok, %{body: b}} -> {:error, "PR create failed: #{inspect(b)}"}
      {:error, e} -> {:error, inspect(e)}
    end
  end

  defp auth_headers(token) do
    [
      {"authorization", "Bearer #{token}"},
      {"accept", "application/vnd.github+json"},
      {"x-github-api-version", "2022-11-28"}
    ]
  end
end
