defmodule Bizforge.CodeReview.GitlabAdapter do
  @moduledoc """
  GitLab Merge Request adapter — creates branches, opens MRs, manages reviews
  via the GitLab v4 REST API (using Req).
  """
  @behaviour Bizforge.CodeReview.Adapter

  require Logger

  @impl true
  def open_pr(issue, project, opts \\ []) do
    binding = opts[:binding]
    config = resolve_config(binding, project)

    branch_name = "bizforge/issue-#{String.slice(issue.id, 0..7)}"
    title = issue.title
    description = "Auto-generated by BizForge for issue #{issue.id}\n\n#{issue.description || ""}"

    case create_branch(config, branch_name) do
      :ok ->
        case create_merge_request(config, branch_name, title, description) do
          {:ok, mr_data} ->
            {:ok,
             %{
               adapter: __MODULE__,
               pr_id: to_string(mr_data["iid"]),
               pr_url: mr_data["web_url"],
               branch_name: branch_name,
               status: "open"
             }}

          {:error, reason} ->
            {:error, reason}
        end

      {:error, reason} ->
        {:error, reason}
    end
  end

  @impl true
  def get_diff(%{pr_id: pr_id}) do
    {:ok, "(GitLab diff for MR !#{pr_id} — fetch via API)"}
  end

  @impl true
  def add_comment(%{pr_id: pr_id}, comment, _opts \\ []) do
    Logger.info("[GitlabAdapter] Comment on MR !#{pr_id}: #{String.slice(comment, 0..50)}")
    {:ok, %{id: "gl-note-#{System.unique_integer([:positive])}", body: comment}}
  end

  @impl true
  def approve(%{pr_id: _pr_id} = handle) do
    {:ok, %{handle | status: "approved"}}
  end

  def approve_and_notify(handle, issue_id) do
    case approve(handle) do
      {:ok, updated} ->
        Bizforge.TaskLifecycle.notify_review_approved(issue_id)
        {:ok, updated}

      err ->
        err
    end
  end

  @impl true
  def request_changes(handle, _reason) do
    {:ok, %{handle | status: "changes_requested"}}
  end

  def request_changes_and_notify(handle, reason, issue_id) do
    case request_changes(handle, reason) do
      {:ok, updated} ->
        Bizforge.TaskLifecycle.notify_changes_requested(issue_id)
        {:ok, updated}

      err ->
        err
    end
  end

  @impl true
  def merge(handle) do
    {:ok, %{handle | status: "merged"}}
  end

  defp resolve_config(binding, _project) do
    integration =
      if binding, do: Bizforge.Repo.get(Bizforge.Schemas.Integration, binding.integration_id), else: nil

    config = if integration, do: integration.config || %{}, else: %{}
    secrets = fetch_secrets(binding)

    %{
      token: secrets["token"] || System.get_env("GITLAB_TOKEN") || "",
      project_id: config["project_id"] || "",
      base_url: config["base_url"] || "https://gitlab.com",
      base_branch: config["default_branch"] || "main"
    }
  end

  defp fetch_secrets(nil), do: %{}

  defp fetch_secrets(binding) do
    import Ecto.Query
    alias Bizforge.Schemas.{IntegrationSecret, Secret}

    Bizforge.Repo.all(
      from is in IntegrationSecret,
        join: s in Secret,
        on: is.secret_id == s.id,
        where: is.integration_id == ^binding.integration_id,
        select: {is.key, s.encrypted_value}
    )
    |> Map.new()
  end

  defp create_branch(config, branch_name) do
    url = "#{config.base_url}/api/v4/projects/#{URI.encode_www_form(config.project_id)}/repository/branches"

    case Req.post(url,
           json: %{branch: branch_name, ref: config.base_branch},
           headers: auth_headers(config.token)
         ) do
      {:ok, %{status: 201}} -> :ok
      {:ok, %{status: 400}} -> :ok
      {:ok, %{body: b}} -> {:error, "Branch create failed: #{inspect(b)}"}
      {:error, e} -> {:error, inspect(e)}
    end
  end

  defp create_merge_request(config, branch_name, title, description) do
    url =
      "#{config.base_url}/api/v4/projects/#{URI.encode_www_form(config.project_id)}/merge_requests"

    body = %{
      source_branch: branch_name,
      target_branch: config.base_branch,
      title: title,
      description: description
    }

    case Req.post(url, json: body, headers: auth_headers(config.token)) do
      {:ok, %{status: 201, body: data}} -> {:ok, data}
      {:ok, %{body: b}} -> {:error, "MR create failed: #{inspect(b)}"}
      {:error, e} -> {:error, inspect(e)}
    end
  end

  defp auth_headers(token) do
    [{"private-token", token}]
  end
end
